steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'builds'
      - 'submit'
      - '--pack=image=gcr.io/derrickwong-default/anthos-spring-demo'
# images:
#   - 'gcr.io/derrickwong-default/anthos-spring-demo'

